//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2021 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class input {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal input() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2021.input", typeof(input).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 195
        ///197
        ///201
        ///204
        ///203
        ///216
        ///213
        ///215
        ///216
        ///185
        ///188
        ///190
        ///205
        ///218
        ///237
        ///243
        ///248
        ///278
        ///289
        ///292
        ///304
        ///313
        ///314
        ///317
        ///329
        ///328
        ///329
        ///328
        ///329
        ///330
        ///331
        ///329
        ///333
        ///337
        ///338
        ///345
        ///352
        ///354
        ///355
        ///359
        ///360
        ///363
        ///365
        ///364
        ///370
        ///371
        ///367
        ///387
        ///403
        ///407
        ///409
        ///411
        ///416
        ///425
        ///435
        ///444
        ///445
        ///446
        ///460
        ///449
        ///454
        ///458
        ///459
        ///463
        ///464
        ///445
        ///447
        ///448
        ///450
        ///452
        ///463
        ///464
        ///475
        ///459
        ///460
        ///465
        ///477
        ///484
        ///485
        ///486
        ///498
        ///500
        ///501
        ///502
        ///516
        ///515
        ///531
        ///534
        ///560
        ///576
        ///583
        ///586
        ///587
        ///575
        ///588
        ///587
        ///591
        ///595
        ///599
        ///607
        ///608
        ///609
        ///61 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day1 {
            get {
                return ResourceManager.GetString("day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 199
        ///200
        ///208
        ///210
        ///200
        ///207
        ///240
        ///269
        ///260
        ///263.
        /// </summary>
        internal static string day1Alternate {
            get {
                return ResourceManager.GetString("day1Alternate", resourceCulture);
            }
        }
    }
}
