//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2021 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class input {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal input() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2021.input", typeof(input).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 195
        ///197
        ///201
        ///204
        ///203
        ///216
        ///213
        ///215
        ///216
        ///185
        ///188
        ///190
        ///205
        ///218
        ///237
        ///243
        ///248
        ///278
        ///289
        ///292
        ///304
        ///313
        ///314
        ///317
        ///329
        ///328
        ///329
        ///328
        ///329
        ///330
        ///331
        ///329
        ///333
        ///337
        ///338
        ///345
        ///352
        ///354
        ///355
        ///359
        ///360
        ///363
        ///365
        ///364
        ///370
        ///371
        ///367
        ///387
        ///403
        ///407
        ///409
        ///411
        ///416
        ///425
        ///435
        ///444
        ///445
        ///446
        ///460
        ///449
        ///454
        ///458
        ///459
        ///463
        ///464
        ///445
        ///447
        ///448
        ///450
        ///452
        ///463
        ///464
        ///475
        ///459
        ///460
        ///465
        ///477
        ///484
        ///485
        ///486
        ///498
        ///500
        ///501
        ///502
        ///516
        ///515
        ///531
        ///534
        ///560
        ///576
        ///583
        ///586
        ///587
        ///575
        ///588
        ///587
        ///591
        ///595
        ///599
        ///607
        ///608
        ///609
        ///61 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day1 {
            get {
                return ResourceManager.GetString("day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 199
        ///200
        ///208
        ///210
        ///200
        ///207
        ///240
        ///269
        ///260
        ///263.
        /// </summary>
        internal static string day1Alternate {
            get {
                return ResourceManager.GetString("day1Alternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward 3
        ///down 4
        ///forward 3
        ///up 4
        ///down 4
        ///down 6
        ///down 3
        ///down 1
        ///up 7
        ///down 7
        ///forward 4
        ///forward 7
        ///forward 3
        ///down 2
        ///forward 5
        ///down 7
        ///forward 5
        ///up 9
        ///down 6
        ///forward 8
        ///forward 8
        ///down 8
        ///forward 7
        ///down 9
        ///down 4
        ///down 6
        ///forward 1
        ///down 2
        ///down 7
        ///up 4
        ///forward 8
        ///down 5
        ///down 7
        ///down 1
        ///forward 5
        ///down 1
        ///up 1
        ///forward 5
        ///forward 1
        ///down 1
        ///forward 3
        ///up 4
        ///up 4
        ///up 8
        ///up 1
        ///forward 7
        ///down 3
        ///forward 3
        ///forward 3
        ///down 3
        ///down 6
        ///down 7
        ///forward 4
        ///down 2
        ///up 3
        ///forward 5
        ///forward 1
        ///down 3
        ///up [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day2 {
            get {
                return ResourceManager.GetString("day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward 5
        ///down 5
        ///forward 8
        ///up 3
        ///down 8
        ///forward 2.
        /// </summary>
        internal static string day2Alternate {
            get {
                return ResourceManager.GetString("day2Alternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101011111001
        ///100100110111
        ///101010101011
        ///010100010000
        ///001101101101
        ///110001101010
        ///001001011001
        ///101111101111
        ///110001001000
        ///111111000000
        ///111100110001
        ///101100010100
        ///000010000011
        ///000110000011
        ///101010100101
        ///000111001010
        ///100101101110
        ///111111010101
        ///110010001100
        ///000011001101
        ///001001111110
        ///100101001100
        ///000011100100
        ///000100110011
        ///000101101000
        ///101010011011
        ///101011110000
        ///010010110011
        ///110110101110
        ///001110000110
        ///001110111101
        ///110111100101
        ///000010101010
        ///101010101010
        ///011011001101
        ///110110000111
        ///01101001 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day3 {
            get {
                return ResourceManager.GetString("day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00100
        ///11110
        ///10110
        ///10111
        ///10101
        ///01111
        ///00111
        ///11100
        ///10000
        ///11001
        ///00010
        ///01010.
        /// </summary>
        internal static string day3Alternate {
            get {
                return ResourceManager.GetString("day3Alternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17,2,33,86,38,41,4,34,91,61,11,81,3,59,29,71,26,44,54,89,46,9,85,62,23,76,45,24,78,14,58,48,57,40,21,49,7,99,8,56,50,19,53,55,10,94,75,68,6,83,84,88,52,80,73,74,79,36,70,28,37,0,42,98,96,92,27,90,47,20,5,77,69,93,31,30,95,25,63,65,51,72,60,16,12,64,18,13,1,35,15,66,67,43,22,87,97,32,39,82
        ///
        ///10 27 53 91 86
        ///15 94 47 38 61
        ///32 68  8 88  9
        ///35 84  3  7 87
        ///62 78 90 66 64
        ///
        ///30 51 26 16 57
        ///66 88 47 75 23
        ///61 77 64  9 73
        ///44 32 28 80 81
        /// 3 99 67 49 78
        ///
        ///68 92 82 74 83
        ///12 99 80 72  3
        ///56 96 36 28 43
        /// 2  7 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day4 {
            get {
                return ResourceManager.GetString("day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1
        ///
        ///22 13 17 11  0
        /// 8  2 23  4 24
        ///21  9 14 16  7
        /// 6 10  3 18  5
        /// 1 12 20 15 19
        ///
        /// 3 15  0  2 22
        /// 9 18 13 17  5
        ///19  8  7 25 23
        ///20 11 10 24  4
        ///14 21 16 12  6
        ///
        ///14 21 17 24  4
        ///10 16 15  9 19
        ///18  8 23 26 20
        ///22 11 13  6  5
        /// 2  0 12  3  7.
        /// </summary>
        internal static string day4Alternate {
            get {
                return ResourceManager.GetString("day4Alternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 529,822 -&gt; 529,562
        ///106,230 -&gt; 568,230
        ///709,377 -&gt; 708,376
        ///600,544 -&gt; 600,638
        ///75,351 -&gt; 70,351
        ///147,959 -&gt; 89,959
        ///626,911 -&gt; 626,805
        ///542,816 -&gt; 408,950
        ///489,224 -&gt; 489,441
        ///266,583 -&gt; 255,583
        ///603,145 -&gt; 603,309
        ///50,871 -&gt; 785,136
        ///460,412 -&gt; 966,918
        ///506,920 -&gt; 506,552
        ///378,515 -&gt; 378,538
        ///16,467 -&gt; 26,467
        ///646,219 -&gt; 646,142
        ///341,461 -&gt; 891,461
        ///382,253 -&gt; 382,945
        ///489,344 -&gt; 634,199
        ///563,19 -&gt; 233,349
        ///337,894 -&gt; 936,295
        ///156,413 -&gt; 156,916
        ///859,986 -&gt; 99,226
        ///226,768 -&gt; 178,816
        ///924,58 -&gt; 924,890
        ///7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day5 {
            get {
                return ResourceManager.GetString("day5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,9 -&gt; 5,9
        ///8,0 -&gt; 0,8
        ///9,4 -&gt; 3,4
        ///2,2 -&gt; 2,1
        ///7,0 -&gt; 7,4
        ///6,4 -&gt; 2,0
        ///0,9 -&gt; 2,9
        ///3,4 -&gt; 1,4
        ///0,0 -&gt; 8,8
        ///5,5 -&gt; 8,2.
        /// </summary>
        internal static string day5Alternate {
            get {
                return ResourceManager.GetString("day5Alternate", resourceCulture);
            }
        }
    }
}
