//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCodeCSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCodeCSharp.data", typeof(data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1652
        ///1998
        ///1677
        ///1855
        ///1955
        ///1875
        ///1993
        ///1860
        ///1752
        ///1936
        ///1816
        ///1924
        ///1872
        ///2000
        ///1967
        ///1882
        ///1737
        ///1801
        ///1832
        ///1985
        ///1933
        ///1911
        ///1894
        ///1384
        ///1871
        ///1607
        ///1858
        ///1950
        ///222
        ///1931
        ///1635
        ///1960
        ///1909
        ///1884
        ///1921
        ///1959
        ///1981
        ///1920
        ///1684
        ///1734
        ///1490
        ///1632
        ///1935
        ///1982
        ///217
        ///1874
        ///1646
        ///1943
        ///986
        ///1509
        ///1899
        ///1834
        ///1908
        ///1769
        ///1989
        ///1977
        ///1436
        ///1973
        ///1974
        ///1941
        ///1624
        ///2006
        ///1867
        ///843
        ///2003
        ///1838
        ///1904
        ///1892
        ///1972
        ///1957
        ///1890
        ///1540
        ///1578
        ///1845
        ///1912
        ///1947
        ///1847
        ///1841
        ///1793
        ///2005
        ///1716
        ///1852
        ///1865
        ///1532
        ///1800
        ///1949
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day1 {
            get {
                return ResourceManager.GetString("day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15-16 f: ffffffffffffffhf
        ///6-8 b: bbbnvbbb
        ///6-10 z: zhzzzzfzzzzzzzzzpzz
        ///9-13 s: dmssskssqsssssf
        ///5-6 v: hvvgvrm
        ///1-8 s: sssssssssss
        ///1-3 x: kxxx
        ///2-5 c: cckgxcnswc
        ///10-11 j: rjjpwdzkfjj
        ///8-11 r: wkrtlrxcskjglb
        ///3-6 l: mqrnhllxx
        ///5-6 z: zzzzlg
        ///12-13 x: qkrqxtrtsfxpnxg
        ///3-7 k: tsbkkkk
        ///4-11 j: jjjrjjjjjjjjjjj
        ///2-4 c: ccccc
        ///2-15 h: hhkhhhhhhhhhhhth
        ///7-8 k: hgcjkxhkskk
        ///3-10 s: ksxgrkcwfsxrqs
        ///10-14 z: hblznxdzxzzzrz
        ///5-8 z: mknrjhzzrjzl
        ///2-4 v: vqvvjhl
        ///3-5 q: fvzqrq
        ///9-13 f: flfpkfvffdfcz
        ///1-7 b: tbbbbbxbb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day2 {
            get {
                return ResourceManager.GetString("day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .........#..##..#..#........#..
        ///#...#..#..#...##.....##.##.#...
        ///....#..............#....#....#.
        ///#.#..#.....#...#.##..#.#.#.....
        ///........#..#.#..#.......#......
        ///.#........#.#..###.#....#.#.#..
        ///........#........#.......#.....
        ///...##..#.#.#........##.........
        ///#.#.##..###............#...#...
        ///............#....#.......###.##
        ///....##....##..#........#......#
        ///............#.#..........#.....
        ///#.#....#....##...#.....#.....#.
        ///......#.#.#...#.....###....#..#
        ///...........##..#.........#..#.#
        ///..#..#........... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day3 {
            get {
                return ResourceManager.GetString("day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ecl:grn
        ///cid:315 iyr:2012 hgt:192cm eyr:2023 pid:873355140 byr:1925 hcl:#cb2c03
        ///
        ///byr:2027 hcl:ec0cfd ecl:blu cid:120
        ///eyr:1937 pid:106018766 iyr:2010 hgt:154cm
        ///
        ///byr:1965 eyr:2028 hgt:157cm
        ///cid:236 iyr:2018 ecl:brn
        ///hcl:#cfa07d pid:584111467
        ///
        ///eyr:2029 ecl:hzl
        ///iyr:1972 byr:1966
        ///pid:2898897192
        ///hgt:59cm hcl:z
        ///
        ///pid:231652013 hcl:#602927 hgt:166
        ///ecl:grn eyr:2025
        ///byr:2008 iyr:1986
        ///
        ///byr:1928 hgt:167cm
        ///hcl:#18171d iyr:2012
        ///ecl:oth pid:237657808 eyr:1944
        ///
        ///hgt:73in ecl:grn byr:1931 pid:358388825 iy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day4 {
            get {
                return ResourceManager.GetString("day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pid:087499704 hgt:74in ecl:grn iyr:2012 eyr:2030 byr:1980
        ///hcl:#623a2f
        ///
        ///eyr:2029 ecl:blu cid:129 byr:1989
        ///iyr:2014 pid:896056539 hcl:#a97842 hgt:165cm
        ///
        ///hcl:#888785
        ///hgt:164cm byr:2001 iyr:2015 cid:88
        ///pid:545766238 ecl:hzl
        ///eyr:2022
        ///
        ///iyr:2010 hgt:158cm hcl:#b6652a ecl:blu byr:1944 eyr:2021 pid:093154719.
        /// </summary>
        internal static string day4test {
            get {
                return ResourceManager.GetString("day4test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFBFBBBRLR
        ///BBFFBFFRRR
        ///BFFFFBBRRR
        ///FFBFFBBLRR
        ///FFBFBFBLLL
        ///FFBFFBFLRR
        ///BFFFBBBLLR
        ///FFBFBFFRLR
        ///FFBFFFBRRR
        ///FFBFFFFRRL
        ///BFFBBFFLRL
        ///FFFBFFBLRR
        ///FBBFBFFRLR
        ///BFFFBFBRLR
        ///BFBFFBBRLR
        ///FFBBFBBLRR
        ///BFBBBFBRLR
        ///FFBBBFBRRL
        ///FFBFBBBRRR
        ///BFBBBBFRLL
        ///FBBFFFBRRR
        ///BFFBFBFRRR
        ///FFBFBBBLRL
        ///FBFFFFBLLR
        ///BBFFBFBRLL
        ///FBBBFFBLRL
        ///FBBBFFFRRR
        ///BFBFFBFRLR
        ///BFFFFBBLLL
        ///FBFFBBFRLR
        ///BFBBBBBLLR
        ///FFFFBBFLRR
        ///FBFBFBFRLR
        ///FBFFBFFLRR
        ///FFBFFBFRRR
        ///BFFBFBFRLL
        ///BFFFBBBLRR
        ///FFBBFFFLLR
        ///FBBBFBBLRR
        ///FFBBFBFRRL
        ///BFFBFFBRLL
        ///FBFFFBBLLR
        ///BFFFBFBL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day5 {
            get {
                return ResourceManager.GetString("day5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heqznia
        ///cipkn
        ///gvsitwynrxb
        ///
        ///auz
        ///zaeu
        ///uaz
        ///zau
        ///zua
        ///
        ///ctqaibd
        ///tbqlzaywvd
        ///bqdtcazls
        ///qtrdvab
        ///hpbtadq
        ///
        ///e
        ///e
        ///je
        ///e
        ///e
        ///
        ///ilzuqnjhrceay
        ///jakzylrnuqcih
        ///uhyqijldrzwnac
        ///
        ///lxtwyiuqerd
        ///sfdmpjawvolkbzqnih
        ///ldtiewgq
        ///
        ///absdepjhctyfzxnivom
        ///fdvbjnsolpztgywmaihx
        ///tkashzxmjbydivfnrop
        ///ptnsojahvxmbdzfiy
        ///
        ///hd
        ///dh
        ///hd
        ///dh
        ///
        ///bup
        ///ktul
        ///
        ///rjfzdhowqnystc
        ///ubfkxhagiqmvplw
        ///
        ///cvknztpwls
        ///cvxtwlq
        ///tcvwxl
        ///
        ///gnusktbacrxodwiyjmzpfhv
        ///dipokyjubnhfsmzxtwga
        ///
        ///lcitb
        ///ctli
        ///cilt
        ///ictl
        ///ilct
        ///
        ///gwpctaiv
        ///fgqvptawch
        ///pgli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day6 {
            get {
                return ResourceManager.GetString("day6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vibrant purple bags contain 3 shiny lavender bags, 1 mirrored gray bag, 4 muted bronze bags.
        ///posh crimson bags contain 4 drab plum bags, 5 dotted purple bags, 3 vibrant lavender bags, 2 striped plum bags.
        ///pale cyan bags contain 5 drab violet bags, 2 dotted crimson bags.
        ///dim lime bags contain 1 muted purple bag, 2 striped silver bags.
        ///clear aqua bags contain 2 plaid green bags.
        ///bright teal bags contain 4 shiny crimson bags, 3 faded red bags, 2 posh lavender bags.
        ///clear white bags contain 1 pale olive b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day7 {
            get {
                return ResourceManager.GetString("day7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vibrant purple bags contain 3 shiny lavender bags, 1 mirrored gray bag, 4 muted bronze bags.
        ///posh crimson bags contain 4 drab plum bags, 5 dotted purple bags, 3 vibrant lavender bags, 2 striped plum bags.
        ///pale cyan bags contain 5 drab violet bags, 2 dotted crimson bags.
        ///dim lime bags contain 1 muted purple bag, 2 striped silver bags.
        ///clear aqua bags contain 2 plaid green bags.
        ///bright teal bags contain 4 shiny crimson bags, 3 faded red bags, 2 posh lavender bags.
        ///clear white bags contain 1 pale olive b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day7test {
            get {
                return ResourceManager.GetString("day7test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acc +28
        ///jmp +481
        ///nop +87
        ///acc -10
        ///acc +21
        ///jmp +548
        ///jmp +250
        ///acc -9
        ///acc +19
        ///acc -3
        ///nop +85
        ///jmp +84
        ///acc +43
        ///acc +34
        ///acc -5
        ///jmp +602
        ///nop +416
        ///acc +19
        ///acc +46
        ///acc +33
        ///jmp +133
        ///acc -3
        ///acc +5
        ///jmp +143
        ///nop -18
        ///acc +50
        ///acc +0
        ///acc -6
        ///jmp +243
        ///acc +11
        ///acc -18
        ///jmp +501
        ///acc +45
        ///jmp +449
        ///acc +0
        ///acc -10
        ///acc +20
        ///nop +516
        ///jmp +544
        ///jmp +551
        ///nop +59
        ///nop +247
        ///acc -1
        ///jmp +589
        ///acc +41
        ///jmp +457
        ///jmp +102
        ///acc +22
        ///jmp +195
        ///acc +30
        ///jmp -38
        ///acc +21
        ///nop -3
        ///jmp +466
        ///acc +47
        ///acc +4
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day8 {
            get {
                return ResourceManager.GetString("day8", resourceCulture);
            }
        }
    }
}
